<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("Спецтехника");
?>
<?php
$APPLICATION->IncludeComponent(
    "bitrix:news",
    "products",
    array(
        "ADD_ELEMENT_CHAIN" => "Y",
        "ADD_SECTIONS_CHAIN" => "Y",
        "AJAX_MODE" => "N",
        "AJAX_OPTION_ADDITIONAL" => "",
        "AJAX_OPTION_HISTORY" => "N",
        "AJAX_OPTION_JUMP" => "N",
        "AJAX_OPTION_STYLE" => "Y",
        "BROWSER_TITLE" => "-",
        "CACHE_FILTER" => "N",
        "CACHE_GROUPS" => "Y",
        "CACHE_TIME" => "36000000",
        "CACHE_TYPE" => "A",
        "CHECK_DATES" => "Y",
        "COMPOSITE_FRAME_MODE" => "A",
        "COMPOSITE_FRAME_TYPE" => "AUTO",
        "DETAIL_ACTIVE_DATE_FORMAT" => "d.m.Y",
        "DETAIL_DISPLAY_BOTTOM_PAGER" => "Y",
        "DETAIL_DISPLAY_TOP_PAGER" => "N",
        "DETAIL_FIELD_CODE" => array(
            0 => "",
            1 => "",
        ),
        "DETAIL_PAGER_SHOW_ALL" => "Y",
        "DETAIL_PAGER_TEMPLATE" => "",
        "DETAIL_PAGER_TITLE" => "",
        "DETAIL_PROPERTY_CODE" => array(
            0 => "ATT_PRICE",
            1 => "ATT_DETAIL_TEXT",
            2 => "ATT_TYPE_AERIAL_PLATFORM",
            3 => "ATT_MAX_HEIGHT",
            4 => "ATT_LIFTING_CAPACITY",
            5 => "ATT_HOIST",
            6 => "ATT_HOIST_DIMENSIONS",
            7 => "ATT_DIMENSIONS_W_D_H",
            8 => "ATT_WIDTH_WITH_SUPPORTS",
            9 => "ATT_MASS",
            10 => "ATT_JIB_LENGTH",
            11 => "ATT_BOOM_CAPACITY",
            12 => "ATT_BODY_LOAD_CAPACITY",
            13 => "ATT_DIMENSIONS_L_W",
            14 => "ATT_BOOM_LENGTH",
            15 => "",
        ),
        "DETAIL_SET_CANONICAL_URL" => "Y",
        "DISPLAY_BOTTOM_PAGER" => "Y",
        "DISPLAY_DATE" => "Y",
        "DISPLAY_NAME" => "N",
        "DISPLAY_PICTURE" => "Y",
        "DISPLAY_PREVIEW_TEXT" => "Y",
        "DISPLAY_TOP_PAGER" => "N",
        "FORM_BACKGROUND_COLOR" => "primary",
        "FORM_ELEMENT_ID" => "",
        "FORM_IBLOCK_ID" => "",
        "FORM_IBLOCK_TYPE" => "primary_content",
        "FORM_POSITION" => "3",
        "GROUP_PERMISSIONS" => array(
            0 => "1",
        ),
        "HIDE_LINK_WHEN_NO_DETAIL" => "N",
        "IBLOCK_ID" => "1",
        "IBLOCK_TYPE" => "primary_content",
        "INCLUDE_IBLOCK_INTO_CHAIN" => "N",
        "LIST_ACTIVE_DATE_FORMAT" => "d.m.Y",
        "LIST_FIELD_CODE" => array(
            0 => "",
            1 => "",
        ),
        "LIST_PROPERTY_CODE" => array(
            0 => "ATT_PRICE",
            1 => "ATT_TYPE_AERIAL_PLATFORM",
            2 => "ATT_MAX_HEIGHT",
            3 => "ATT_LIFTING_CAPACITY",
            4 => "ATT_HOIST",
            5 => "ATT_DIMENSIONS_W_D_H",
            6 => "ATT_JIB_LENGTH",
            7 => "ATT_BOOM_CAPACITY",
            8 => "ATT_BODY_LOAD_CAPACITY",
            9 => "ATT_DIMENSIONS_L_W",
            10 => "",
        ),
        "MESSAGE_404" => "",
        "META_DESCRIPTION" => "-",
        "META_KEYWORDS" => "-",
        "NEWS_COUNT" => "20",
        "PAGER_BASE_LINK_ENABLE" => "N",
        "PAGER_DESC_NUMBERING" => "N",
        "PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
        "PAGER_SHOW_ALL" => "N",
        "PAGER_SHOW_ALWAYS" => "N",
        "PAGER_TEMPLATE" => "main_pagination",
        "PAGER_TITLE" => "",
        "PREVIEW_TRUNCATE_LEN" => "",
        "SEF_FOLDER" => "/spetstekhnika/",
        "SEF_MODE" => "Y",
        "SET_LAST_MODIFIED" => "Y",
        "SET_STATUS_404" => "N",
        "SET_TITLE" => "Y",
        "SHOW_404" => "N",
        "SHOW_FORM_BLOCK" => "N",
        "SMALL_CARD_TAG_TITLE" => "2",
        "SORT_BY1" => "SORT",
        "SORT_BY2" => "ACTIVE_FROM",
        "SORT_ORDER1" => "ASC",
        "SORT_ORDER2" => "DESC",
        "STRICT_SECTION_CHECK" => "Y",
        "USE_CATEGORIES" => "N",
        "USE_FILTER" => "N",
        "USE_PERMISSIONS" => "N",
        "USE_RATING" => "N",
        "USE_RSS" => "N",
        "USE_SEARCH" => "N",
        "USE_SHARE" => "N",
        "COMPONENT_TEMPLATE" => "products",
        "SECTIONS_SMALL_CARD_TAG_TITLE" => "2",
        "SEF_URL_TEMPLATES" => array(
            "news" => "",
            "section" => "#SECTION_CODE#/",
            "detail" => "#SECTION_CODE#/#ELEMENT_CODE#/",
        )
    ),
    false
); ?>
<?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>